version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo-client
      - redis-client
    networks:
      - mern-network

  mongo-client:
    container_name: mongo-client
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./server/.docker/mongo/data/db:/data/db
    networks:
      - mern-network

  redis-client:
    container_name: redis-client
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./server/.docker/redis/data:/data
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
