version: "3"
services:
  frontend:
    build: ./client
    container_name: react_ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
    - backend
    networks:
      - mern-network
  backend:
    build: ./server
    container_name: node-api
    ports:
      - "5000:5000"
    depends_on:
    - database
    networks:
      - mern-network
  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "5000:5000"
    volume:
      - /home/mongo-backup:/data/db
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge



  

